# server:
#   image: node:7
#   command: npm start
#   working_dir: /app
#   volumes:
#     - .:/app
#   environment:
#     PORT: 3000

#   ports:
#     - "3000:3000"
#   links:
#       - db
# db:
#   image: postgres
#   expose:
#     - 5432
#   volumes:
#     - ./seed.sql:/docker-entrypoint-initdb.d/seed.sql
#   environment:
#     POSTGRES_PASSWORD: password
#     POSTGRES_USER: user
#     POSTGRES_DB: titanic_db

version: '3'

services:

  server:
    build: ./
    expose: 
      - 4567
    environment:
      API_HOST: "localhost:3001"
      APP_SERVER_PORT: 4567
    ports: 
      - 4567:4567
    volumes: 
      - ./:/srv/app/server/src
    command: npm run start


  client:
    build: ./client
    environment:
      - REACT_APP_PORT=3000
    expose: 
      - 3000
    ports:
      - 3000:3000
    volumes:
      - ./client/src:/srv/app/client/src
      - ./client/public:/srv/app/client/public
    links:
      - server
    command: npm run start

  db:
    image: "postgres:latest"
    restart: always
    container_name: "titanic_db"
    ports:
      - "54320:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: titanic_db
    volumes:
      - ./seed.sql:/docker-entrypoint-initdb.d/seed.sql
volumes:
  my_dbdata: